### ISSUE TITLE
Configure Parse Server

### ISSUE THREAD

**Issue by kavyasahai** [kavyasahai/shortRecipes#1]
- [ ] Deploy to Heroku
- [ ] Test Deployment
- [ ] Setup local parse dashboard
- [ ]  Add parse Client to Project

**Comment by codepathreview** [comment]
Not Updated ReadMe:

- Updated status of issues in Project board	Required	2pts
- Sprint planned for next week -- Issues created, assigned & added to project board	Required	3pts
- Completed user stories checked-off in README	Required	2pts
- Gifs created to show build progress and added to README	Required	3pts 
/cc @codepathreview

**Comment by shabari8695** [comment]
These were split and handled as separate issues.
